services:
  auth:
    container_name: arlequimtech-auth
    build:
      dockerfile: ArlequimTech.Auth.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=arlequimtech;Username=test12345;Password=test12345
    depends_on:
      - postgres
  products:
    container_name: arlequimtech-products
    build:
      dockerfile: ArlequimTech.Product.API/Dockerfile
    ports:
      - "8085:8085"
      - "8086:8086"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=arlequimtech;Username=test12345;Password=test12345
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  stock:
    container_name: arlequimtech-stock
    build:
      dockerfile: ArlequimTech.Stock.API/Dockerfile
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=arlequimtech;Username=test12345;Password=test12345
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  order:
    container_name: arlequimtech-order
    build:
      dockerfile: ArlequimTech.Order.API/Dockerfile
    ports:
      - "8095:8095"
      - "8096:8096"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=arlequimtech;Username=test12345;Password=test12345
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: arlequimtech-postgres
    environment:
      POSTGRES_USER: test12345
      POSTGRES_PASSWORD: test12345
      POSTGRES_DB: arlequimtech
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:latest
    container_name: arlequimtech-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres_data:
  rabbitmq_data:
