services:
  auth:
    container_name: arlequimtech-auth
    build:
      dockerfile: ArlequimTech.Auth.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=arlequimtech;Username=test12345;Password=test12345
    depends_on:
      - postgres
  products:
    container_name: arlequimtech-products
    build:
      dockerfile: ArlequimTech.Product.API/Dockerfile
    ports:
      - "8085:8085"
      - "8086:8086"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=arlequimtech;Username=test12345;Password=test12345
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: arlequimtech-postgres
    environment:
      POSTGRES_USER: test12345
      POSTGRES_PASSWORD: test12345
      POSTGRES_DB: arlequimtech
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
